applySpecVersion: 1
spec:
  configSync: 
    enabled: true
    sourceType: git
    sourceFormat: unstructured
    syncRepo: https://github.com/Gkemhcs/kustomize-config-management.git
    policyDir: proj
    syncBranch: main
    secretType: none