 
resources:
- ../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-two
nameSuffix: team2
replicas:
- name: deployment
  count: 2
commonAnnotations:
   type: kustomize
   version: 2.0.0