
resources:
- ../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-one
nameSuffix: team1
replicas:
- name: deployment
  count: 1
commonAnnotations:
   type: kustomize
   version: 1.0.0